require 'rspec/matchers'
require 'capybara'
require 'capybara/dsl'
# require 'dotenv'
# require 'money'
require 'rubyXL'

module Harness
  # Dotenv.load
end

# require 'harness/helpers/date_helpers'
require_relative '../features/support/bootbox'
require_relative '../features/support/java_script_helper'
# require 'harness/page_object'
require 'harness/page_object/home_page'
# require 'harness/page_objects/activity_dashboard'
# require 'harness/page_objects/excel_utility'
# require 'harness/page_objects/activity_detail'
# require 'harness/page_objects/add_employee'
# require 'harness/page_objects/benefit_page'
# require 'harness/page_objects/transaction_page'
# require 'harness/page_objects/policy_search_page'
# require 'harness/page_objects/view_all_benefits'
# require 'harness/page_objects/member_search'
# require 'harness/page_objects/bulk_salary'
# require 'harness/page_objects/upload_salary'
# require 'harness/page_objects/view_transactions_page'
# require 'harness/page_objects/employee_information/employee_information_page'
# require 'harness/page_objects/employee_information/contact_area'
# require 'harness/page_objects/employee_information/update_contacts_page'
# require 'harness/page_objects/employee_information/terminate_employee'
# require 'harness/page_objects/employee_information/change_billing_division'
# require 'harness/page_objects/employee_information/change_billing_category'
# require 'harness/page_objects/employee_information/benefit_area'
# require 'harness/page_objects/employee_information/update_employee_information'
# require 'harness/page_objects/employee_information/update_family_enrollment'
# require 'harness/page_objects/employee_information/enroll_benefit'
# require 'harness/page_objects/member_list'
# require 'harness/page_objects/employee_information/tobacco_information'
# require 'harness/page_objects/employee_information/employment_details_area'
# require 'harness/page_objects/employee_information/spouse_form'
# require 'harness/page_objects/exception_activity/exception_activity_page'
# require 'harness/page_objects/exception_activity/view_exceptions_page'
# require 'harness/page_objects/upload_employee_data_page'

# require 'harness/data/data'
# require 'harness/data/data_adapter'
# require 'harness/data/termination_reason'